openapi: 3.1.0
info:
  title: Identity Provider - API
  version: 0.0.1
  description: |-
    Identify Provider - API
paths:
  /authenticate/password:
    post:
      summary: Authenticate a user by the password
      requestBody:
        content:
          application/json:
            $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        200:
          content:
            application:json:
              $ref: '#/components/schemas/AuthenticationResponse'
  /register:
    post:
      summary: User registration
    requestBody:
      content:
        application/json:
          $ref: '#/component/schemas/RegistrationRequest'
    responses:
      201:
        headers:
          Location:
            schema:
              type: string
      400:
        content:
          application/json:
            $ref: '#/component/schemas/ErrorResponse'
components:
  schemas:
    CredentialRequest:
      type: object
      properties:
        userId:
          type: string
        password:
          type: string
    AuthenticationRequest:
      allOf:
        - $ref: '#/components/schemas/CredentialRequest'
    AuthenticationResponse:
      type: object
      properties:
        pseudonym:
          description: temporary alias of the user Id
          type: string
    RegistrationRequest:
      allOf:
        - $ref: '#/components/schemas/CredentialRequest'
    ErrorResponse:
      type: object
      properties:
        type:
          type: string
        timestamp:
          type: string
          format: datetime
