(import (rnrs)
	(mpm context)
	(mpm configurations)
	(mpm idp apis)
	(text yaml)
	(util concurrent)
	(getopt)
	(srfi :197)
	(pp))

(define (usage file)
  (print file " -c $config")
  (exit 1))

(define (main args)
  (with-args args
      ((config  (#\c "config") #t (usage (car args)))
       . ignore)
    (let* ((v (car (call-with-input-file config yaml-read)))
	   (ctx (configuration->execution-context (json->configuration v))))
      (pp (chain (register ctx "ktakashi@ymail.com" "TestPassword1234!")
		 (future-flatmap
		  (lambda (registred?)
		    (authenticate ctx "ktakashi@ymail.com" "TestPassword1234!"))
		  _)
		 (future-get _))))))
